---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
pca <- read_table2("/Users/valishashah/codes/plink/plink_mac_20201019/acs_mini_project.eigenvec", col_names = FALSE)
eigenval <- scan("/Users/valishashah/codes/plink/plink_mac_20201019/acs_mini_project.eigenval")

```
Q1
```{r}
library(dplyr)
pca_new <- pca %>%
  select(1:21)
pca_new
```

```{r}
write.csv(pca_new, 'acs_mini_pca.csv')
```

```{r}

pca <- pca[,-1]
# set names
names(pca)[1] <- "ind"
names(pca)[2:ncol(pca)] <- paste0("PC", 1:(ncol(pca)-1))
pca
```


```{r}
# sort out the individual species and pops
# spp
spp <- rep(NA, length(pca$ind))
spp[grep("PunPund", pca$ind)] <- "pundamilia"
spp[grep("PunNyer", pca$ind)] <- "nyererei"
# locationc
loc <- rep(NA, length(pca$ind))
loc[grep("Mak", pca$ind)] <- "makobe"
loc[grep("Pyt", pca$ind)] <- "python"
# combine - if you want to plot each in different colours
spp_loc <- paste0(spp, "_", loc)

```


```{r}
pca <- as.tibble(data.frame(pca, spp, loc, spp_loc))
```


```{r}

pve <- data.frame(PC = 1:20, pve = eigenval/sum(eigenval)*100)
pve

```

```{r}
a <- ggplot(pve, aes(PC, pve)) + geom_bar(stat = "identity")
a + ylab("Percentage variance explained") + theme_light()

```
````{r}
cumsum(pve$pve)

```


```{r}

# plot pca
b <- ggplot(pca, aes(PC1, PC2, col = spp, shape = loc)) + geom_point(size = 3)
b <- b + scale_colour_manual(values = c("red", "blue"))
b <- b + coord_equal() + theme_light()
b + xlab(paste0("PC1 (", signif(pve$pve[1], 3), "%)")) + ylab(paste0("PC2 (", signif(pve$pve[2], 3), "%)"))

```











